apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bugswarm-worker-queue
spec:
  scaleTargetRef:
    name: bugswarm-worker
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: redis
      metadata:
        address: redis.bugswarm.svc.cluster.local:6379
        databaseIndex: "0"
        listName: celery
        listLength: "4"
